version: '2'
services:
  weighttracker-app:
    image: weighttracker
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://weighttracker-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=weightTracker
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  weighttracker-mongodb:
    extends:
      file: mongodb.yml
      service: weighttracker-mongodb
